version: '3.3'

services:
  web:
    build: .
    command: gunicorn EdukarApi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./EdukarApi/.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 8001:80
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./EdukarApi/.env

volumes:
  pgdata:
  static_volume:
  media_volume: