services:
  web:
    build: .
    command: gunicorn EdukarApi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - logs_volume:/home/app/web/logs
    expose:
      - 8000
    env_file:
      - ./EdukarApi/.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 8000:80
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    env_file:
      - ./EdukarApi/.env
  redis:
    image: redis:alpine
  huey:
    build: .
    command: python manage.py run_huey
    volumes:
      - media_volume:/home/app/web/media
    depends_on:
      - db
      - redis
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
  logs_volume:
