# Generated by Django 4.0.3 on 2025-01-01 02:59

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='receipt',
            field=models.FileField(null=True, upload_to=store.models.Sell.receipt_upload_to),
        ),
    ]
