# Generated by Django 4.0.3 on 2025-01-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('part_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='video_parts', to='store.product')),
            ],
            options={
                'ordering': ['part_number'],
                'unique_together': {('product', 'part_number')},
            },
        ),
    ]
