# Generated by Django 4.0.3 on 2025-01-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_videopart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='on_cart_at',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='on_pending_at',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='payment_image',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='status',
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sell',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sell',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sell',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
