# Generated by Django 4.0.3 on 2025-02-02 06:47

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_sell_on_cart_at_remove_sell_on_pending_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=store.models.Sell.receipt_upload_to),
        ),
    ]
