# Generated by Django 4.0.3 on 2025-02-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_sell_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('currency_code', models.CharField(max_length=10)),
                ('expiration_date', models.IntegerField(blank=True, null=True)),
                ('client_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
