# Generated by Django 4.0.3 on 2025-06-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_order_rename_sell_metadata_sell_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='order_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
