# Generated by Django 4.0.3 on 2025-03-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_order_rename_sell_metadata_sell_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
