# Generated by Django 4.0.3 on 2025-07-28 13:54

from django.db import migrations, models
import django_resized.forms
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_sell_order_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WebP', keep_meta=True, null=True, quality=50, scale=None, size=[400, 566], upload_to=store.models.Product.product_upload_to),
        ),
    ]
