# Generated by Django 4.0.3 on 2023-01-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnivExamsStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('siglas', models.CharField(max_length=25)),
                ('exam_type', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='cover/')),
                ('year', models.IntegerField()),
                ('source_exam', models.URLField()),
                ('source_video_solution', models.URLField()),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.univexamsstructure')),
            ],
        ),
    ]
