# Generated by Django 4.0.3 on 2023-01-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='source_video_solution',
            field=models.URLField(blank=True),
        ),
    ]
