# Generated by Django 4.0.3 on 2023-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_exams_source_video_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='source_video_solution_premium',
            field=models.URLField(blank=True),
        ),
    ]
