# Generated by Django 4.0.3 on 2024-07-19 04:03

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='slug',
            field=models.SlugField(blank=True, max_length=125, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, null=True, quality=50, scale=None, size=[400, 566], upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, null=True, quality=50, scale=None, size=[400, 566], upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.univexamsstructure'),
        ),
    ]
