# Generated by Django 4.0.3 on 2024-11-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_exams_slug_alter_course_image_alter_exams_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='source_exam',
            field=models.CharField(max_length=200),
        ),
    ]
