# Generated by Django 4.0.3 on 2025-03-01 23:22

from django.db import migrations, models
import django_resized.forms
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productcomment'),
        ('services', '0011_alter_university_exam_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WebP', keep_meta=True, null=True, quality=50, scale=None, size=[400, 566], upload_to=services.models.Exams.upload_cover),
        ),
        migrations.AlterField(
            model_name='exams',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='exams', to='store.product'),
        ),
    ]
