# Generated by Django 4.0.3 on 2025-07-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_sell_order_at'),
        ('services', '0012_alter_exams_cover_alter_exams_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='products',
        ),
        migrations.AddField(
            model_name='exams',
            name='source_video_product',
            field=models.ForeignKey(blank=True, help_text='Producto de tipo Video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='store.product'),
        ),
    ]
