"""
Django settings for EdukarApi project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

# Importing environment variables from .env file.
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG") in ("True",)
ENVIRONMENT = env("ENVIRONMENT")

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS").split(" ")

CSRF_TRUSTED_ORIGINS = env("DJANGO_CSRF_TRUSTED_ORIGINS").split(" ")

# Application definition

INSTALLED_APPS = [
    # Custom apps installed
    "account",
    "forum",
    "notification",
    "store",
    "services",
    "core",
    "dashboard",
    "webhooks",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Packages installed
    "rest_framework",
    "rest_framework.authtoken",
    "djoser",
    "corsheaders",
    "huey.contrib.djhuey",
    "django_cleanup",
]

# Change defualt storage when running test
# Avoid storing image in media file when running tests.
if "test" in sys.argv:
    # store files in memory, no cleanup after tests are finished
    DEFAULT_FILE_STORAGE = "inmemorystorage.InMemoryStorage"
    # much faster password hashing, default one is super slow (on purpose)
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]

# Rest Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "forum": "2/day",
    },
}

# Configuración para aplicar el login con email.
AUTH_AUTHENTICATION_TYPE = "both"

AUTHENTICATION_BACKENDS = ("core.backends.EmailOrUsernameModelBackend",)

DJOSER = {
    "PASSWORD_RESET_CONFIRM_URL": "account/reset-password/{uid}/{token}",
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    "USERNAME_RESET_CONFIRM_URL": "username/reset/confirm/{uid}/{token}",
    "ACTIVATION_URL": "account/activate/{uid}/{token}",
    "SEND_ACTIVATION_EMAIL": True,
    "SERIALIZERS": {
        "user_create": "account.serializers.UserProfileSerializer",
        "current_user": "account.serializers.UserProfileInfoSerializer",
    },
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "EdukarApi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "EdukarApi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("DBENGINE"),
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("DBHOST"),
        "PORT": "",
    }
}

# Cloudflare Buckets env
CF_ACCOUNT_ID = os.environ.get("CF_ACCOUNT_ID")
CF_VIDEO_IMAGE_TOKEN = os.environ.get("CF_VIDEO_IMAGE_TOKEN")

# env for public exams
EXAMS_ACCESS_KEY_ID = os.environ.get("EXAMS_R2_ACCESS_KEY_ID")
EXAMS_SECRET_ACCESS_KEY = os.environ.get("EXAMS_R2_SECRET_ACCESS_KEY")
EXAMS_BUCKET_NAME = os.environ.get("EXAMS_R2_BUCKET_NAME")

# Culqi token
CULQI_API_KEY = os.environ.get("CULQI_API_KEY")

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

if not DEBUG:
    # Get Redis cconf environment
    REDIS_HOST = env("REDIS_HOST")
    REDIS_PORT = env("REDIS_PORT")

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": "redis://{}:{}".format(REDIS_HOST, REDIS_PORT),
        }
    }

# Huey settings
HUEY = {
    "huey_class": "huey.RedisHuey",  # Huey implementation to use.
    "name": DATABASES["default"]["NAME"],  # Use db name for huey.
    "immediate": env(
        "HUEY_IMMEDIATE",
        default=False,  # If False, run synchronously.
    ),
    "connection": {
        "host": env("REDIS_HOST"),
        "port": 6379,
        "db": 0,
        # huey-specific connection parameters.
    },
}

RUNNING_TESTS = "test" in sys.argv

if RUNNING_TESTS:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": True,  # Desactiva todos los loggers durante tests
    }

else:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
                "style": "{",
            },
            "simple": {
                "format": "{levelname} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "file": {
                "level": "INFO",
                "formatter": "verbose",
                "filename": os.path.join(BASE_DIR, "logs", "logs.log"),
                "class": "logging.handlers.TimedRotatingFileHandler",
                "when": "midnight",
                "interval": 1,
                "backupCount": 7,  # keep this number of rotated files
                "encoding": "utf-8",  # ensure file is written with utf-8 encoding
                "delay": True,  # open file only when needed
            },
            "console": {
                "level": "DEBUG",
                "class": "logging.StreamHandler",
                "formatter": "simple",
            },
        },
        "loggers": {
            "django.security.DisallowedHost": {
                "handlers": ["file", "console"],
                "level": "ERROR",
                "propagate": False,
            },
            "django.request": {
                "handlers": ["file", "console"],
                "level": "ERROR",
                "propagate": False,
            },
            "": {
                "handlers": ["file", "console"],
                "level": "DEBUG",
                "propagate": True,
            },
        },
    }

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "es-PE"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS").split(" ")

STATIC_URL = "static/"
MEDIA_URL = "media/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Frontend values
DOMAIN = env("DOMAIN")
SITE_NAME = env("SITE_NAME")

# For Django Email Backend
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
