# Generated by Django 4.0.3 on 2025-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhooksEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_payload', models.JSONField(null=True)),
                ('webhook', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'webhooks_events',
            },
        ),
    ]
