# Generated by Django 4.0.3 on 2022-10-10 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0006_comment_remove_post_likes_reply_comment_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('notif_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_type', to='notification.notificationtypes')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_sent', to=settings.AUTH_USER_MODEL)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_post', to='forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
