# Generated by Django 4.0.3 on 2022-10-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtypes',
            old_name='description',
            new_name='desc_receiver',
        ),
        migrations.AddField(
            model_name='notificationtypes',
            name='desc_sender',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
