# Generated by Django 4.0.3 on 2024-05-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_description_notificationtypes_desc_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='source_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='NotificationTypes',
        ),
    ]
