# Generated by Django 4.0.3 on 2024-04-22 06:32

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_profile_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=account.models.UserImage.image_upload)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('module', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
