# Generated by Django 4.0.3 on 2022-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default-avatar.jpg', upload_to='profile/'),
        ),
    ]
