# Generated by Django 4.0.3 on 2024-05-12 22:37

import account.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='default-avatar.jpg', force_format='WebP', keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to=account.models.Profile.image_upload),
        ),
    ]
