# Generated by Django 4.0.3 on 2022-03-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Cursos', (('aritmetica', 'Aritmética'), ('rm', 'Razonamiento Matemático'), ('quimica', 'Química'))), ('articulos-y-noticias', 'Artículos y Noticias')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
