# Generated by Django 4.0.3 on 2022-03-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_section_slug_subsection_slug_alter_post_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.subsection'),
        ),
    ]
