# Generated by Django 4.0.3 on 2022-12-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_remove_post_likes_reply_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.subsection'),
        ),
    ]
