# Generated by Django 4.0.3 on 2024-05-07 13:56

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_post_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to=forum.models.BaseContentPublication.image_upload),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=forum.models.BaseContentPublication.image_upload),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(null=True, upload_to=forum.models.BaseContentPublication.image_upload),
        ),
    ]
